import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import AppLayout from "@/components/layout/AppLayout";
import { QueryProvider } from "@/components/providers/QueryProvider";
import { AddMarkerDrawerWrapper } from "@/features/Map/components/AddMarkerDrawerWrapper";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const apiKey = process.env.NEXT_PUBLIC_YANDEX_MAPS_API_KEY;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <Script
          src={`https://api-maps.yandex.ru/v3/?apikey=${apiKey}&lang=ru_RU`}
          strategy="beforeInteractive"
        />
      </head>
      <body className="min-h-full">
        <QueryProvider>
          <AppLayout>{children}</AppLayout>
          <AddMarkerDrawerWrapper />
        </QueryProvider>
      </body>
    </html>
  );
}
