import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { ConfigProvider, App } from 'antd';
import AppLayout from "@/layout/AppLayout";
import { QueryProvider } from "@/providers/QueryProvider";
import { AddSupplierDrawerWrapper } from "@/features/SupplierDrawerControll";
import "./globals.css";
import "./drawer-styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const apiKey = process.env.NEXT_PUBLIC_YANDEX_MAPS_API_KEY;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen overflow-hidden">
        <Script
          src={`https://api-maps.yandex.ru/v3/?apikey=${apiKey}&lang=ru_RU`}
          strategy="beforeInteractive"
        />
        <QueryProvider>
          <ConfigProvider
            theme={{
              components: {
                Drawer: {
                  colorBgElevated: '#f3f4f6',
                  colorBgMask: 'rgba(0,0,0,0.3)',
                  borderRadiusLG: 12,
                  footerPaddingBlock: 16,
                  footerPaddingInline: 16,
                },
              },
            }}
          >
            <App>
              <AppLayout>{children}</AppLayout>
              <AddSupplierDrawerWrapper />
            </App>
          </ConfigProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
